services:
  spring-boot-app:
    container_name: backend
    image: jobis-backend  # Docker에서 빌드한 Spring Boot 애플리케이션 이미지 이름
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ACCESS_EXPIRED: ${JWT_ACCESS_EXPIRED}
      JWT_REFRESH_EXPIRED: ${JWT_REFRESH_EXPIRED}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      NAVER_CLIENT_ID: ${NAVER_CLIENT_ID}
      NAVER_CLIENT_SECRET: ${NAVER_CLIENT_SECRET}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}

  vue-app:
    container_name: frontend
    image: jobis-front
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      VITE_APP_API_URL: ${VITE_APP_API_URL}

networks:
  default:
    external:
      name: jobis-network
